name: Build OrangeFox hero2lte

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y \
          git \
          curl \
          python3 \
          repo \
          ccache \
          openjdk-11-jdk \
          zip \
          unzip


    - name: Initialize OrangeFox
      run: |
        mkdir fox
        cd fox

        repo init \
          -u https://gitlab.com/OrangeFox/Manifest.git \
          -b fox_16.0


    - name: Add device manifest
      run: |
        cd fox

        mkdir -p .repo/local_manifests

        cp ../local_manifests/roomservice.xml \
        .repo/local_manifests/


    - name: Sync source
      run: |
        cd fox

        repo sync \
          -c \
          --force-sync \
          --no-clone-bundle \
          -j$(nproc)


    - name: Setup build environment
      run: |
        cd fox

        source build/envsetup.sh

        lunch twrp_hero2lte-eng


    - name: Build recovery
      run: |
        cd fox

        source build/envsetup.sh

        lunch twrp_hero2lte-eng

        mka recoveryimage


    - name: Upload recovery
      uses: actions/upload-artifact@v4
      with:
        name: OrangeFox-hero2lte
        path: fox/out/target/product/hero2lte/recovery.img
